/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.movietiketbooking;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.border.MatteBorder;

/**
 *
 * @author sumit
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
     MovieData db = new MovieData();
    
    public DashBoard(int u_id) {
        this.u_id= u_id;
        initComponents();
       int count= db.rowCount();
       int[]no= db.getid();
     
       System.out.print(no);
       if(no!=null)
       {
         jPanel1.setLayout(new GridLayout(3,3,3,3));
        for(int i=0;i<count;i++)
        {
                db.getDetails(no[i]);
             JPanel b= this.Shows(db.name,db.screen,db.time,db.image,db.language,db.id);
             jPanel1.add(b);
        }
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Your Show");

        jTextField1.setToolTipText("Search Movies");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );

        jPanel1.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s =jTextField1.getText();
        if(s.equals(""))
        {
            jPanel1.repaint();
            jPanel1.removeAll();
            int count= db.rowCount();
         jPanel1.setLayout(new GridLayout(3,3,3,3));
        for(int i=0;i<count;i++)
        {
                db.getDetails(i+1);
             JPanel b= this.Shows(db.name,db.screen,db.time,db.image,db.language,db.id);
             jPanel1.add(b);
        }
        }else{
            int id=  db.getid(s);
           if(id==0){
           
           jPanel1.repaint();
            jPanel1.removeAll();
           JLabel lblNewLabel = new JLabel("");
		lblNewLabel.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\noresultsfound.png"));
		lblNewLabel.setBounds(95, 47, 219, 129);
		jPanel1.add(lblNewLabel);
		
		JLabel lblNewLabel_1 = new JLabel("Oops! no such result found");
		lblNewLabel_1.setFont(new Font("Tahoma", Font.PLAIN, 18));
		lblNewLabel_1.setBounds(95, 181, 229, 25);
		jPanel1.add(lblNewLabel_1);
          
           }else{
            jPanel1.repaint();
            jPanel1.removeAll();
            jPanel1.setLayout(new GridLayout(3,3,3,3));
            for(int i=0;i<1;i++)
            {
                db.getDetails(id);
                JPanel b= this.Shows(db.name,db.screen,db.time,db.image,db.language,db.id);
                jPanel1.add(b);
            }}}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginPage a = new LoginPage(u_id);
        a.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard(0).setVisible(true);
            }
        });
    }
 public  JPanel Shows(String name,String screen ,String time,ImageIcon icon ,String lang,int id) {
        JPanel a = new JPanel();
		a.setLayout(null);
		a.setBorder(new LineBorder(new Color(0, 0, 0)));
		
                JLabel lblNewLabel = new JLabel();
		lblNewLabel.setIcon(icon);
		lblNewLabel.setBorder(new LineBorder(new Color(0, 0, 0)));
		lblNewLabel.setBounds(10, 1, 168, 221);
		a.add(lblNewLabel);
		
		JButton btnNewButton = new JButton("BOOK");
		btnNewButton.setBorder(new MatteBorder(2, 2, 2, 2, (Color) Color.BLUE));
		btnNewButton.setBounds(188, 161, 136, 34);
		a.add(btnNewButton);
		
		JLabel scrren_language = new JLabel("Scrren - " +screen+ " Language -" +lang);
		scrren_language.setBounds(188, 109, 244, 41);
		a.add(scrren_language);
		
		JLabel ltime = new JLabel("Time - "+time);
		ltime.setBounds(188, 56, 244, 34);
		a.add(ltime);
		
		JLabel Name = new JLabel(name);
		Name.setBounds(188, 11, 244, 34);
		a.add(Name);

                btnNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           if(u_id==0)
           {
               JOptionPane.showMessageDialog(null, "Please Login First then try to book","Error",0);
           }
           else{
               int c = seatCount();
               Booking bk = new Booking(id,c,u_id);
               bk.setVisible(true);
               setVisible(false);
           }
            }
        });     return a;
	}
 public static int count = 1;
 public  int seatCount( ){
   
                di = new JDialog(this , "Select Seats", true);
		di.setSize(685, 475);
		di.setLayout(null);
		ButtonGroup G = new ButtonGroup();
		
		JLabel lblNewLabel = new JLabel("How Many Seats?");
		lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 19));
		lblNewLabel.setBounds(189, 21, 253, 47);
		di.add(lblNewLabel);
		
		 JLabel lblNewLabel_1  = new JLabel("");
                 lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\scooter.jpg"));
		lblNewLabel_1.setForeground(Color.WHITE);
		
		lblNewLabel_1.setBounds(176, 79, 336, 210);
		di.add(lblNewLabel_1);
		
		JRadioButton rdbtnNewRadioButton = new JRadioButton("1");
		rdbtnNewRadioButton.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton.setBounds(127, 321, 44, 34);
		rdbtnNewRadioButton.setSelected(true);
		G.add(rdbtnNewRadioButton);
		di.add(rdbtnNewRadioButton);
		rdbtnNewRadioButton.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                           lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\scooter.jpg"));
                           DashBoard.count=1;
                         }
                     });   
		
		JRadioButton rdbtnNewRadioButton_1 = new JRadioButton("2");
		rdbtnNewRadioButton_1.setBounds(173, 321, 51, 34);
		rdbtnNewRadioButton_1.setFont(new Font("Tahoma", Font.BOLD, 18));
		G.add(rdbtnNewRadioButton_1);
		di.add(rdbtnNewRadioButton_1);
		rdbtnNewRadioButton_1.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                         lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\scooter.jpg"));
                          DashBoard.count=2;
                         }
                     });  
                
		JRadioButton rdbtnNewRadioButton_2 = new JRadioButton("3");
		rdbtnNewRadioButton_2.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton_2.setBounds(226, 321, 44, 34);
		G.add(rdbtnNewRadioButton_2);
		di.add(rdbtnNewRadioButton_2);
		rdbtnNewRadioButton_2.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\s.jpg"));
                              DashBoard.count=3;
                         }
                     });   
		
		JRadioButton rdbtnNewRadioButton_3 = new JRadioButton("4");
		rdbtnNewRadioButton_3.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton_3.setBounds(284, 327, 44, 23);
		G.add(rdbtnNewRadioButton_3);
		di.add(rdbtnNewRadioButton_3);
		rdbtnNewRadioButton_3.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                            lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\s.jpg"));
                             DashBoard.count=4;
                         }
                     });  
		
		JRadioButton rdbtnNewRadioButton_4 = new JRadioButton("5");
		rdbtnNewRadioButton_4.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton_4.setBounds(330, 327, 44, 23);
		G.add(rdbtnNewRadioButton_4);
		di.add(rdbtnNewRadioButton_4);
		rdbtnNewRadioButton_4.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\car.jpg"));
                              DashBoard.count=5;
                         }
                     });   
		
		JRadioButton rdbtnNewRadioButton_5 = new JRadioButton("6");
		rdbtnNewRadioButton_5.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton_5.setBounds(376, 327, 44, 23);
		G.add(rdbtnNewRadioButton_5);
		di.add(rdbtnNewRadioButton_5);
		rdbtnNewRadioButton_5.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                            lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\car.jpg"));
                             DashBoard.count=6;
                         }
                     });   
		
		JRadioButton rdbtnNewRadioButton_5_1 = new JRadioButton("7");
		rdbtnNewRadioButton_5_1.setBounds(422, 327, 44, 23);
		rdbtnNewRadioButton_5_1.setFont(new Font("Tahoma", Font.BOLD, 18));
		G.add(rdbtnNewRadioButton_5_1);
		di.add(rdbtnNewRadioButton_5_1);
		rdbtnNewRadioButton_5_1.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             
                           lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\car.jpg"));
                            DashBoard.count=7;
                         }
                     });   
		
		JRadioButton rdbtnNewRadioButton_5_2 = new JRadioButton("8");
		rdbtnNewRadioButton_5_2.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton_5_2.setBounds(468, 327, 44, 23);
		G.add(rdbtnNewRadioButton_5_2);
		di.add(rdbtnNewRadioButton_5_2);
		rdbtnNewRadioButton_5_2.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                            lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\Bus.jpg"));
                             DashBoard.count=8;
                         }
                     });  
		
		JRadioButton rdbtnNewRadioButton_5_3 = new JRadioButton("9");
		rdbtnNewRadioButton_5_3.setBounds(514, 327, 44, 23);
		rdbtnNewRadioButton_5_3.setFont(new Font("Tahoma", Font.BOLD, 18));
		G.add(rdbtnNewRadioButton_5_3);
		di.add(rdbtnNewRadioButton_5_3);
		rdbtnNewRadioButton_5_3.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                            lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\Bus.jpg"));
                             DashBoard.count=9;
                         }
                     });   
		
		JRadioButton rdbtnNewRadioButton_5_4 = new JRadioButton("10");
		rdbtnNewRadioButton_5_4.setBounds(560, 327, 58, 23);
		rdbtnNewRadioButton_5_4.setFont(new Font("Tahoma", Font.BOLD, 18));
		G.add(rdbtnNewRadioButton_5_4);
		rdbtnNewRadioButton_5_4.addActionListener(new ActionListener(){
                         @Override
                         public void actionPerformed(ActionEvent e) {
                           lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\sumit\\Desktop\\pic\\Bus.jpg"));
                            DashBoard.count=10;
                         }
                     });  
		di.add(rdbtnNewRadioButton_5_4);
                
                JButton btnNewButton = new JButton("Select Seats");
		btnNewButton.setFont(new Font("Tahoma", Font.BOLD, 17));
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
                             di.setVisible(false);
			}
		});
		btnNewButton.setBounds(249, 389, 161, 34);
		di.add(btnNewButton);
                di.setVisible(true);
        return count;
 } 
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    public static JDialog di;  
    public int  u_id;
}
